### ISSUE TITLE
text mode: mangled characters in indented titles

### ISSUE THREAD

**Issue by Octachron** [maranget/hevea#12]
Compiling the following document with `hevea -text`
```latex
\documentclass{book}
\begin{document}
  \begin{quote}
     \subsubsection{A subsubsection}
   \end{quote}
\end{document}
```
results in the following output
```
   A subsubsection
\00\00---------------
```
The invalid characters inserted at the start are random (they change with the contents of the file).
This is probably one of the issue affecting the OCaml manual in ocaml/ocaml#9242 .
(I may look at the issue myself in the upcoming week).

**Comment by maranget** [comment]
Dear @Octachron thank you for your precise and detailled bug report. I am investigating.

**Comment by maranget** [comment]
The bug is hopefully corrected in master branch. Ask if a release is needed.

Thanks again.

**Comment by Octachron** [comment]
Trying to compile the manual with the hevea master branch now yields a fatal error:

> Fatal error: exception Invalid_argument("index out of bounds")

**Comment by maranget** [comment]
Oups...

**Comment by maranget** [comment]
Hi @Octachron, it should be ok by now. I have also tested https://github.com/ocaml/ocaml/issues/9242.

**Comment by Octachron** [comment]
Indeed the issue seems fixed now, thanks!

I don't really need a release right now, it would be nice if there was one by the time of the release of OCaml 4.11 (around July?) but even there I can use the master version of hevea.
