### ISSUE TITLE
HTML attribute `lang'

### ISSUE THREAD

**Issue by cspiel** [maranget/hevea#25]
We would benefit from some flexible support for the `lang` attribute
to get [automatic hyphenation](http://clagnut.com/blog/2395) into Hevea-translated documents.

For a start, having `<html lang="LANG">` with LANG cleverly filled in
should be enough for monolingual documents.  Multilingual documents
require a finer-grained application, which can already be achieved
through the built-in macro `\@open@par[ATTRIBUTES]`.

**Comment by maranget** [comment]
> For a start, having `<html lang="LANG">` with LANG cleverly filled in
I guess that package babel could be responsible for setting this parameter. It is doable quite easily I guess, by using `\AtBeginDocument`.


> should be enough for monolingual documents. Multilingual documents
> require a finer-grained application, which can already be achieved
> through the built-in macro `\@open@par[ATTRIBUTES]`.
Hum.

**Comment by maranget** [comment]
Solved by https://github.com/maranget/hevea/pull/26
