### ISSUE TITLE
Hevea in OPAM is behind...

### ISSUE THREAD

**Issue by pmetzger** [maranget/hevea#3]
I note that the Hevea in OPAM is 2.29, while the released Hevea is 2.32. Perhaps this could be updated? If necessary I may be able to help.

**Comment by maranget** [comment]
> I note that the Hevea in OPAM is 2.29, while the released Hevea is 2.32. Perhaps this could be updated? If necessary I may be able to help.
> 
Hi,

Good catch, I am not the maintainer of hevea package on opam.
According to opam.ocaml.org Pierre Boutillier is. And yes we should sort
this out for a better update of the package. Any help will be welcome :)

--Luc

**Comment by pmetzger** [comment]
I've now submitted an update of the package. See: https://github.com/ocaml/opam-repository/pull/12282

**Comment by pmetzger** [comment]
It's done.

**Comment by maranget** [comment]
Thanks a lot for this opam release.
