### ISSUE TITLE
RFC: use SVG in Hevea-generated HTML?

### ISSUE THREAD

**Issue by cspiel** [maranget/hevea#46]
Hi everybody -

I want to translate the LaTeX macro `\rule[raise_len]{wdth}{hght}` as faithful as possible.
Currently my most promising approach uses SVG.  The question is: do we allow for SVG or
does it exclude too many browsers/applications?

Comments welcome!

**Comment by maranget** [comment]
I have not heard of browsers that would reject SVG. Text-based ones, such as links ?

**Comment by cspiel** [comment]
@maranget: My preferred, text-based browser, `w3m` discards SVG.

As there does not seem to be a strong refusal of SVG in Hevea-generated
documents (after all **hacha** introduces them by default) I close this RFC
and open a P/R that implements LaTeX `\rule` with the help of SVG.
