### ISSUE TITLE
correct use of Zero Width Joiner?

### ISSUE THREAD

**Issue by sanette** [maranget/hevea#60]
This follows up from https://github.com/ocaml/ocaml/issues/10254
When Hevea is applied to the Ocaml manual, it produces section titles like this one:
```
'Chapter\u2004\u200d2\u2003The module system'
```
The \u200d is "[Zero Width Joiner](https://en.wikipedia.org/wiki/Zero-width_joiner)", and AFAIU is supposed to be used to combine two letters (producing ligatures, for instance).
Somewhat strangely here it has the effect that Firefox changes the font of the following char "2".
So I was wondering, maybe this is an incorrect use of this "ZWJ".

**Comment by Octachron** [comment]
I didn't notice that the zero-width joiner was mixing a white space and a number. It does seem unlikely that font renderers would known how to handle such combination. A combination of narrow non-breaking space would probably work better with most font renderer.

**Comment by maranget** [comment]
Merged PR #61 should fix the issue.

**Comment by maranget** [comment]
Since PR #61 has been merged, I close the issue.
