### ISSUE TITLE
Build error on openSUSE 15.3

### ISSUE THREAD

**Issue by drmpjz** [maranget/hevea#65]
Build environment:

openSUSE 15.3

ocaml 4.05.0
ocamlbuild 0.14.0

hevea 2.35 source code

make builds a long list of modules (so in principle build environemnt seems to be sane :-) ) , but eventually fails with 

+ /usr/bin/ocamlopt.opt -c -w +a-3-4-9-41-45-67 -annot -safe-string -o length.cmx length.ml
File "length.mll", line 67, characters 41-52:
Error: Unbound module Float
Command exited with code 2.
make: *** [Makefile:57: ocb-opt] Error 10

Any hints how to fix this would be appreciated.

**Comment by cspiel** [comment]
OCaml 4.05 has no `Float` module (and no `round` function either).

You could ...
- upgrade your OCaml system,
- write your own `round` function, or
- in this particular case, i.e. Hevea module Length, you could get away with simply removing the calls to `Float.round`.

**Comment by drmpjz** [comment]
Thanks a lot! That was exactly what I needed.
I checked the rolling-release version of openSUSE (Tumbleweed), looks  like an upgrade to ocaml 4.12 is in the works there. With this version hevea 2.35 completes the compile (albeit with a few warnings).
Short term workaround (remove Float.round) applied and build completes without issues on my main system(s).
