### ISSUE TITLE
Escape labels/refs to be valid for CSS

### ISSUE THREAD

**Issue by Chris00** [maranget/hevea#7]
In the OCaml manual — and likely in other documents too — the authors use labels containing colons, such as [`c:core-xamples`](https://github.com/ocaml/ocaml/blob/trunk/manual/manual/tutorials/coreexamples.etex#L1), which are used verbatim in HTML, generating `<a id="c:core-xamples"></a>`. While this is valid HTML, these ID [cannot be used in CSS](https://github.com/ocaml/ocaml.org/issues/1093).  It would be nice — possibly specifying an option — that all ID generated by hevea be compabile with CSS.

**Comment by gasche** [comment]
I investigated the production of `id="..."` by Hevea.

Hevea generates unique counters for headings, for example `sec1`, `sec2`, etc., and those are produced by the `\secid` macro in `latexcommon.hva`. Those don't need escaping.

User-defined labels `\section{foo}\label{sec:foo}` are rendered to HTML through the `\locname` macro defined by each backend, in particular in `html/hevea.hva`. Those would need escaping, but I'm not sure whether it's possible to do it programmatically in OCaml, or whether the escape scheme would have to be implemented in TeX...

**Comment by Chris00** [comment]
Thanks for investigating.  It seems they only [need to be escaped in CSS, not HTML](https://github.com/ocaml/ocaml.org/issues/1093#issuecomment-552601992).  Does hevea generates CSS files?

**Comment by gasche** [comment]
Well actually I think this comment (you can use `#foo\:bar` in CSS to select on `foo:bar`) means that no change to Hevea is required, so we can close the present issue.

(Hevea generates CSS files, but they do not contain user-selected labels I think, only a default style.)
