### ISSUE TITLE
hacha fails on `<img />` tags

### ISSUE THREAD

**Issue by xavierleroy** [maranget/hevea#8]
Consider the following `foo.tex` file:
```
\documentstyle{article}
\begin{document}
\begin{rawhtml}
<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a>
\end{rawhtml}
\end{document}
```
Run it through `hevea` then `hacha`:
```
$ hevea foo.tex
$ hacha foo.html 
foo.html:58: Error while reading HTML: intag: attribute syntax
Adios
```
Replace `<img .../>` by `<img ...>` and the problem goes away.

In HTML 5, it is correct to close empty elements such as `img` by writing `<img ... />`.  This should not cause `hacha` to crash.

**Comment by maranget** [comment]
I am afraid you are right.

Thank you for reporting the issue. This deserves a correction.

**Comment by maranget** [comment]
I have committed a fix https://github.com/maranget/hevea/commit/87072c376210ef76195af7a455f84484e76e8580.

If satisfying, this will go into the next release.
